version: '3.0'

services:
   server:
      build: 
         context: .
      command: ./server
      restart: always
      ports:
         - 8000:8000
      networks:
         - proxy

networks:
   default:
      driver: bridge
   proxy:
      external:
         name: proxy
